app:
  telegram-token: 6457058625:AAE5HN6-gl2JJyso37yZv2HFsxm25IcSRjk

spring:
  application:
    name: TrackAndNotifyBot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
