app:
  telegram-token: 6838376936:AAHwLnqciau0H0aksTnz0lY6SINrAz9cnOY

spring:
  application:
    name: TrackAndNotifyBot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
